/**
 * AI Loading Overlay.
 * Displays a centered spinner with messaging while AI generates content.
 * Shows a green success banner at the top when AI has just finished.
 */
"use client";

import { useState, useEffect } from "react";
import { cn } from "@/lib/utils";
import type { IdeaBlock } from "@/types/sandbox-planner";
import { IDEA_BLOCK_LABELS } from "@/types/sandbox-planner";

/** Field names that AI updates per step — shown in the "soon you will have…" message. */
const STEP_FIELDS: Record<IdeaBlock, string[]> = {
  ideas: [],
  structure_align: ["The Core Problem", "Target Audience", "Primary Success Metrics"],
  refining_icp: ["Day in the Life", "Pain Points & Acute Needs"],
  product_definition_flows: ["Product Summary", "Feature List & Logic", "User Flows"],
  strategic_frameworks: [
    "Value Proposition",
    "JTBD Synthesis",
    "ICP Architect",
    "NABC Pitch",
    "Optimization Suggestions",
  ],
};

interface AiLoadingOverlayProps {
  /** The step currently being generated by AI. */
  step: IdeaBlock;
  /** Whether the AI has just completed (show success banner). */
  justCompleted?: boolean;
}

/** Full-area overlay shown while AI is generating content for a step. */
export default function AiLoadingOverlay({
  step,
  justCompleted = false,
}: AiLoadingOverlayProps) {
  const [showSuccess, setShowSuccess] = useState(justCompleted);

  // Auto-dismiss success banner after 5 seconds
  useEffect(() => {
    if (!showSuccess) return;
    const timer = setTimeout(() => setShowSuccess(false), 5000);
    return () => clearTimeout(timer);
  }, [showSuccess]);

  // Show success banner when justCompleted changes to true
  useEffect(() => {
    if (justCompleted) setShowSuccess(true);
  }, [justCompleted]);

  const fields = STEP_FIELDS[step] ?? [];
  const fieldList = fields.join(", ");

  if (showSuccess && !justCompleted) return null;

  return (
    <div className="relative flex flex-col items-center justify-center min-h-96">
      {/* Success banner */}
      {showSuccess && (
        <div
          className={cn(
            "absolute top-0 left-0 right-0 px-4 py-3 rounded-lg text-sm font-medium text-center",
            "bg-green-500 text-white"
          )}
          role="status"
        >
          Success! Our AI has started updating {fieldList}
        </div>
      )}

      {/* Spinner + message */}
      {!justCompleted && (
        <div className="flex flex-col items-center gap-6 mt-8">
          {/* Animated sparkle circle */}
          <div className="w-24 h-24 rounded-full bg-accent flex items-center justify-center animate-pulse">
            <svg
              className="w-12 h-12 text-white"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path d="M12 2 L13.5 9.5 L21 12 L13.5 14.5 L12 22 L10.5 14.5 L3 12 L10.5 9.5 Z" />
            </svg>
          </div>

          <p className="text-xl font-semibold text-text-primary">
            AI is working...
          </p>
          {fields.length > 0 && (
            <p className="text-sm text-text-muted text-center max-w-sm">
              Soon you will have {fieldList} updated
            </p>
          )}
        </div>
      )}
    </div>
  );
}
